[project]
name = "nyc-taxi-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kenneth McLeod", email = "mcleod.kc@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "dbt-duckdb>=1.11.0",
    "pandas>=3.0.5",
    "polars>=1.44.1",
    "pyarrow>=25.0.1",
    "requests>=2.34.2",
]

[project.scripts]
nyc-taxi-data = "nyc_taxi_data:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.6",
    "sqlfluff>=4.3.0",
]
