name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install Dependencies
        run: uv sync --all-extras --dev

      - name: Run Tests with Coverage
        run: uv run pytest --cov=src/nyc_taxi_data --cov-report=term-missing